services:
  mariadb:
    build: 
      context: requirements/mariadb
    container_name: mariadb
    env_file:
    - .env
    volumes:
    - mariadb_data:/var/lib/mysql
    networks:
    - inception
    restart: always
  
  nginx:
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    env_file:
    - .env
    ports:
    - "443:443"
    networks:
    - inception
    volumes:
    - wordpress_data:/var/www/html 
    #depends_on:
    #- wordpress
    restart: always
  
volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception:
    driver: bridge