services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
    - .env
    volumes:
    - mariadb_data:/var/lib/mysql
    networks:
    - inception
    restart: always
  
volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

networks:
  inception:
    driver: bridge